POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Heroclix - Draft C.U.R.",
    "description": "Torneio de Heroclix com draft de booster de comuns e incomuns.",
    "price": 40,
    "image": "url de banner"
}

###

GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/644291fd45a1fc9bba6be2b5

###
DELETE http://localhost:3000/api/services/644292c745a1fc9bba6be2ba

###
PUT http://localhost:3000/api/services/644291fd45a1fc9bba6be2b5
Content-Type: application/json

{
    "name": "Torneio de Heroclix",
    "description": "Torneio Comuns e Incomuns, Draft",
    "price": 40,
    "image": "url de banner"
}

###
POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Heroclix - Draft C.U.R.",
    "description": "Torneio de Heroclix com draft de booster de comuns e incomuns.",
    "price": 40,
    "image": "url de banner"
}

###
POST http://localhost:3000/api/events
Content-Type: application/json

{
    "title": "Titulo do evento",
    "author": "Autor",
    "description": "Descrição e detalhes",
    "budget": 160,
    "image": "Link de URL",
    "services": [
        {
            "name": "Serviço 1",
            "description": "Descrição do serviço",
            "price": 40,
            "image": "url de banner"
        },
        {
            "name": "Serviço 2",
            "description": "Descrição do serviço",
            "price": 40,
            "image": "url de banner"
        }
    ]
}

###
GET http://localhost:3000/api/events

###
GET http://localhost:3000/api/events/6442b4427918c6b9dd6105ed